language: node_js
node_js:
- lts/*
- node
- iojs
sudo: false
deploy:
  provider: npm
  email: david@davidlday.com
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: ISYplUqT/TdRmOGjHoagd1S+W3HOy2rnyos4nPrhcwlY1hD0kdGNrkF4aW7Yf2qjL3MjGYhVkUl1l7Wsscf4u9GNjPSM8DhiN/oXFrLdeLK8JP0EH8rX6CtJk/7TdDGYK8Shh91kiw/d3o76DBYh46BuW2FaI5l4qaDywaWgoQGS5600PycPe7sEPxixDYr3M/BfdTUpesa6Hf66Oyk5MmvZj+95oW9kJQ27Y/rCvWHsE5VlFCPV9oI23zP4EmNaUbhhYc3+o4B1kcQbCef0lPMN1ubOWlLsOJLqUMTWvk93qvVjMAmCl0bTdnk1mhb8swDeVV8dtO38A6aE4iANHjNWV8J5on3Zmk1ZDjrj4nnFHCMVDuhszijxnP9CUo3fK67RoH/ygIp/vQFBVMR0/kY2GF46cXAIwSMCVXwN1I9XpPAmGJYTSTAga7XczxbW1Y5bbAUXXw77JBmdFHsT0d+QpWf1LRJzqLdZBGfFykWhP7hkCZYdxiBOWiJcdsj4NfoORLT2C7I9kzHHuQ0mchuXTC8P88hr6D2dyAMUG9308PgeAmt/p+JwHHSH3/qPAvCwjBAHALnxToOQPjoi90OOq8KNYsZUlb0Ll4meOzT5V2UFe5CDPNCNuJwYUVrY/VxC1agWIgGctQVIVAXCMwgPRRlQ5sCp+Dw3e+QtNVg=
